// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Monster struct {
	ID     string
	Name   string
	Type   string
	Basehp int32
}

type Move struct {
	ID    string
	Name  string
	Power int32
	Type  string
}

type Movemap struct {
	Monsterid string
	Moveid    string
}

type SchemaMigration struct {
	Version string
}

type Stat struct {
	Monsterid string
	Stattype  string
	Power     int32
}
