// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
)

type Monster struct {
	ID     uuid.UUID
	Name   string
	Type   string
	Basehp int32
}

type Move struct {
	ID    uuid.UUID
	Name  string
	Power int32
	Type  string
}

type Movemap struct {
	Monsterid uuid.UUID
	Moveid    uuid.UUID
}
