// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: monsters.sql

package database

import (
	"context"
)

const listMonsters = `-- name: ListMonsters :many
SELECT id, name, type, basehp FROM monster
`

func (q *Queries) ListMonsters(ctx context.Context) ([]Monster, error) {
	rows, err := q.db.Query(ctx, listMonsters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monster
	for rows.Next() {
		var i Monster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Basehp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
