services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-gkmn}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/local/initdb_scripts:/docker-entrypoint-initdb.d
  migrate:
    image: amacneil/dbmate
    command: >
      --url postgres://postgres:password@postgres:5432/cloud?sslmode=disable up
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations/:/db/migrations
volumes:
  postgres:
networks:
  postgres:
