// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gkmn/v1/gkmn.proto

package gkmnv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/jchapman63/neo-gkmn/internal/service/gkmn/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GkmnServiceName is the fully-qualified name of the GkmnService service.
	GkmnServiceName = "jchapman63.gkmn.v1.GkmnService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GkmnServiceCreateBattleProcedure is the fully-qualified name of the GkmnService's CreateBattle
	// RPC.
	GkmnServiceCreateBattleProcedure = "/jchapman63.gkmn.v1.GkmnService/CreateBattle"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	gkmnServiceServiceDescriptor            = v1.File_gkmn_v1_gkmn_proto.Services().ByName("GkmnService")
	gkmnServiceCreateBattleMethodDescriptor = gkmnServiceServiceDescriptor.Methods().ByName("CreateBattle")
)

// GkmnServiceClient is a client for the jchapman63.gkmn.v1.GkmnService service.
type GkmnServiceClient interface {
	CreateBattle(context.Context, *connect.Request[v1.GkmnServiceCreateBattleRequest]) (*connect.Response[v1.GkmnServiceCreateBattleResponse], error)
}

// NewGkmnServiceClient constructs a client for the jchapman63.gkmn.v1.GkmnService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGkmnServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GkmnServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &gkmnServiceClient{
		createBattle: connect.NewClient[v1.GkmnServiceCreateBattleRequest, v1.GkmnServiceCreateBattleResponse](
			httpClient,
			baseURL+GkmnServiceCreateBattleProcedure,
			connect.WithSchema(gkmnServiceCreateBattleMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// gkmnServiceClient implements GkmnServiceClient.
type gkmnServiceClient struct {
	createBattle *connect.Client[v1.GkmnServiceCreateBattleRequest, v1.GkmnServiceCreateBattleResponse]
}

// CreateBattle calls jchapman63.gkmn.v1.GkmnService.CreateBattle.
func (c *gkmnServiceClient) CreateBattle(ctx context.Context, req *connect.Request[v1.GkmnServiceCreateBattleRequest]) (*connect.Response[v1.GkmnServiceCreateBattleResponse], error) {
	return c.createBattle.CallUnary(ctx, req)
}

// GkmnServiceHandler is an implementation of the jchapman63.gkmn.v1.GkmnService service.
type GkmnServiceHandler interface {
	CreateBattle(context.Context, *connect.Request[v1.GkmnServiceCreateBattleRequest]) (*connect.Response[v1.GkmnServiceCreateBattleResponse], error)
}

// NewGkmnServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGkmnServiceHandler(svc GkmnServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gkmnServiceCreateBattleHandler := connect.NewUnaryHandler(
		GkmnServiceCreateBattleProcedure,
		svc.CreateBattle,
		connect.WithSchema(gkmnServiceCreateBattleMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/jchapman63.gkmn.v1.GkmnService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GkmnServiceCreateBattleProcedure:
			gkmnServiceCreateBattleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGkmnServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGkmnServiceHandler struct{}

func (UnimplementedGkmnServiceHandler) CreateBattle(context.Context, *connect.Request[v1.GkmnServiceCreateBattleRequest]) (*connect.Response[v1.GkmnServiceCreateBattleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("jchapman63.gkmn.v1.GkmnService.CreateBattle is not implemented"))
}
